### ISSUE TITLE
[FEATURE] - Suggested Improvements for Get-RemoteCertificate

### ISSUE THREAD

**Issue by jdhitsolutions** [powershellpr0mpt/PSP-Inventory#10]
I have a few thoughts on this function.

# Remoting
Unlike many of your other commands which rely on a CIM connection, this function does not. When you open the certificate store remotely you are making a legacy RPC/DCOM connection. This means anything in the cloud is inaccessible. As is any machine that has firewall rules blocking this kind of connectivity, which they should. 

The better approach is to use PowerShell Remoting and maybe use Invoke-Command to get certificate information. You might also include an optional parameter for Credential.

## Why not use the CERT: psdrive
When you have connectivity, your command works very nicely. But is there a reason not to use the CERT: PSDrive on the remote machine? Especially if you adopt my first suggestion and use remoting it becomes easy to query and get the same information.

## Other Store Locations
The way your StoreLocation parameter is used suggests there are other options. Probably the only other option is CurrentUser.  If that is the case, then I suggest adding a ValidateSet on the parameter. This has the added effect of offering tab completion on valid values.

**Comment by powershellpr0mpt** [comment]
The reason I'm not using remoting is because I'm currently experiencing issues where remoting is not [properly] enabled in an environment and this solution tends to work in these cases as well.

I'm definitely aware of the fact that this could be done through WinRM, but wanted to make sure I could obtain the information when it's not available too.

As for the other store, because I'm using the `[System.Security.Cryptography.X509Certificates.StoreLocation]` type, it automatically enumerates the possible values for me:

```powershell
[System.Enum]::GetNames('System.Security.Cryptography.X509Certificates.StoreLocation')
CurrentUser
LocalMachine
```

**Comment by jdhitsolutions** [comment]
My turn to bang head on desk. Yes, the typenames automatically enumerate as possible values.
